# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JARVISUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JARVIS(object):
    def setupUi(self, JARVIS):
        JARVIS.setObjectName("JARVIS")
        JARVIS.resize(1152, 825)
        JARVIS.setAnimated(False)
        JARVIS.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(JARVIS)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1151, 791))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("JARVISGIF.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 431, 141))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("INITIATING.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(610, 20, 261, 81))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(870, 20, 261, 81))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(830, 660, 93, 28))
        self.pushButton.setStyleSheet("background-color: rgb(209, 255, 199);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(940, 660, 93, 28))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 195, 175);")
        self.pushButton_2.setObjectName("pushButton_2")
        JARVIS.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JARVIS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1152, 26))
        self.menubar.setObjectName("menubar")
        JARVIS.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JARVIS)
        self.statusbar.setObjectName("statusbar")
        JARVIS.setStatusBar(self.statusbar)

        self.retranslateUi(JARVIS)
        QtCore.QMetaObject.connectSlotsByName(JARVIS)

    def retranslateUi(self, JARVIS):
        _translate = QtCore.QCoreApplication.translate
        JARVIS.setWindowTitle(_translate("JARVIS", "MainWindow"))
        self.pushButton.setText(_translate("JARVIS", "RUN"))
        self.pushButton_2.setText(_translate("JARVIS", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JARVIS = QtWidgets.QMainWindow()
    ui = Ui_JARVIS()
    ui.setupUi(JARVIS)
    JARVIS.show()
    sys.exit(app.exec_())
